### PR TITLE
Add option to read20 to extract all bits from all files

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
The current version of read20 irreversibly mangles and drops bits if forced to extract binary files.

The current options are:

- -T to forcibly treat binary files as text files.
- -c to not drop CR from line endings.

I propose to add a new option, say -b, to:

1. Extract all files.
2. Extract 36-bit words preserving all bits, using "five characters with last bit swizzled".
3. Leave CR LF alone.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Do I make myself clear?

swiz2

**Comment by larsbrinkhoff** [comment]
CC @eswenson1 @lisper @Devon7 @atsampson @kcr

**Comment by eswenson1** [comment]
Go for it. Picture is nice and clear.

**Comment by larsbrinkhoff** [comment]
Pull request submitted.

I verified listing the contents of XX:\<C>-STINK.-IPAK-.9 which was the actual use case for extracting binary files from a TOPS-20 tape.

**Pull request merged**
